name: SPT Release Build - Linux ARM64

on:
  schedule:
    - cron: "0 4 * * *" # Nightly should trigger at 4am UTC (11pm EST).
  repository_dispatch:
    types: [build-trigger]
  workflow_dispatch:
    inputs:
      buildTag:
        description: "The tag to build on"
        required: true
        type: string

concurrency:
  group: spt-release-build-linux-arm64
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    container:
      image: refringe/spt-build-node:1.0.9
    outputs:
      proceed: ${{ steps.check-existence.outputs.proceed }}
      is_nightly: ${{ steps.determine-context.outputs.is_nightly }}
      branch_server: ${{ steps.determine-context.outputs.branch_server }}
      target_tag: ${{ steps.determine-context.outputs.target_tag }}
      build_type: ${{ steps.determine-build-type.outputs.build_type }}
      client_version: ${{ steps.versions.outputs.client_version }}
      spt_version: ${{ steps.versions.outputs.spt_version }}

    steps:
      - name: Determine Build Context
        id: determine-context
        shell: bash
        env:
          EVENT_NAME: ${{ github.event_name }}
          CLIENT_PAYLOAD_TAG: ${{ github.event.client_payload.tag }}
          WORKFLOW_INPUT_TAG: ${{ github.event.inputs.buildTag }}
        run: |
          echo "Determining build context..."
          if [[ "$EVENT_NAME" == "schedule" ]]; then
            echo "is_nightly=true" >> $GITHUB_OUTPUT
            echo "branch_server=4.0.0-DEV" >> $GITHUB_OUTPUT
            echo "Context is nightly build"
          else
            echo "is_nightly=false" >> $GITHUB_OUTPUT
            # Determine the tag based on the event type
            if [[ "$EVENT_NAME" == "workflow_dispatch" ]]; then
              TAG_NAME="$WORKFLOW_INPUT_TAG"
            elif [[ "$EVENT_NAME" == "repository_dispatch" ]]; then
              TAG_NAME="$CLIENT_PAYLOAD_TAG"
            else
              echo "Unsupported event: $EVENT_NAME"
              exit 1
            fi

            if [[ -z "$TAG_NAME" ]]; then
              echo "No tag provided in event payload."
              exit 1
            fi
            echo "target_tag=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "Target tag is $TAG_NAME"
          fi

      - name: Determine Build Type
        id: determine-build-type
        shell: bash
        run: |
          if [[ "${{ steps.determine-context.outputs.is_nightly }}" == "true" ]]; then
            BUILD_TYPE="bleedingmods"
          else
            TARGET_TAG="${{ steps.determine-context.outputs.target_tag }}"
            TARGET_TAG_UPPER="${TARGET_TAG^^}"

            BUILD_TYPE="debug"
            if [[ "$TARGET_TAG_UPPER" =~ -BEM ]]; then
              BUILD_TYPE="bleedingmods"
            elif [[ "$TARGET_TAG_UPPER" =~ -BE ]]; then
              BUILD_TYPE="bleeding"
            elif [[ "$TARGET_TAG_UPPER" =~ v?[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              BUILD_TYPE="release"
            fi
          fi
          echo "build_type=$BUILD_TYPE" >> $GITHUB_OUTPUT
          echo "Build type is $BUILD_TYPE"

      - name: Check Existence
        id: check-existence
        shell: bash
        run: |
          PROCEED="true"
          if [[ "${{ steps.determine-context.outputs.is_nightly }}" == "true" ]]; then
            REPO_URL="https://github.com/sp-tarkov/server.git"
            BRANCH="${{ steps.determine-context.outputs.branch_server }}"
            echo "Checking for branch $BRANCH in Server..."
            if ! git ls-remote --heads $REPO_URL $BRANCH | grep -q $BRANCH; then
              echo "Branch $BRANCH not found in $REPO_URL"
              PROCEED="false"
            fi
          else
            TAG="${{ steps.determine-context.outputs.target_tag }}"
            REPO_URL="https://github.com/sp-tarkov/server.git"
            echo "Checking for tag $TAG in Server..."
            if ! git ls-remote --tags $REPO_URL $TAG | grep -q $TAG; then
              echo "Tag $TAG not found in $REPO_URL"
              PROCEED="false"
            fi
          fi
          echo "proceed=$PROCEED" >> $GITHUB_OUTPUT
          echo "Matches found. Proceeding with build."

      - name: Tag Not Found
        if: steps.check-existence.outputs.proceed == 'false'
        run: |
          echo "Required branch/tag not found in the server repository, halting workflow."
          exit 1

      - name: Extract Versions
        id: versions
        shell: bash
        run: |
          rm -rf /workspace/SPT/Build/server-core
          git init /workspace/SPT/Build/server-core
          cd /workspace/SPT/Build/server-core
          git remote add origin https://github.com/sp-tarkov/server.git
          git config core.sparseCheckout true
          echo "project/assets/configs/core.json" >> .git/info/sparse-checkout

          if [[ "${{ steps.determine-context.outputs.is_nightly }}" == "true" ]]; then
            REF=${{ steps.determine-context.outputs.branch_server }}
          else
            REF=${{ steps.determine-context.outputs.target_tag }}
          fi

          git fetch --depth=1 origin "${REF}"
          git checkout FETCH_HEAD

          cd project/assets/configs
          SPT_VERSION=$(jq -r '.sptVersion' core.json)
          FULL_VERSION=$(jq -r '.compatibleTarkovVersion' core.json)
          CLIENT_VERSION=${FULL_VERSION##*.}

          echo "client_version=$CLIENT_VERSION" >> $GITHUB_OUTPUT
          echo "spt_version=$SPT_VERSION" >> $GITHUB_OUTPUT

          echo "Client version is $CLIENT_VERSION"
          echo "SPT version is $SPT_VERSION"

  build-server:
    needs: prepare
    if: needs.prepare.outputs.proceed == 'true'
    runs-on: ubuntu-latest
    container:
      image: refringe/spt-build-node:1.0.9
    outputs:
      server_commit: ${{ steps.clone-server.outputs.server_commit }}
    steps:
      - name: Clone Server
        id: clone-server
        shell: bash
        run: |
          rm -rf /workspace/SPT/Build/server
          if [[ "${{ needs.prepare.outputs.is_nightly }}" == "true" ]]; then
            BRANCH=${{ needs.prepare.outputs.branch_server }}
            echo "Cloning branch $BRANCH"
            git clone https://github.com/sp-tarkov/server.git --branch "$BRANCH" --depth 1 /workspace/SPT/Build/server
          else
            TAG=${{ needs.prepare.outputs.target_tag }}
            echo "Cloning tag $TAG"
            git clone https://github.com/sp-tarkov/server.git --branch "$TAG" --depth 1 /workspace/SPT/Build/server
          fi

          cd /workspace/SPT/Build/server
          echo "server_commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Pull LFS Files
        shell: bash
        run: |
          cd /workspace/SPT/Build/server
          git lfs install --local
          git lfs pull

      - name: Install Dependencies
        shell: bash
        run: |
          cd /workspace/SPT/Build/server/project
          npm install

      - name: Build Server for Linux ARM64
        shell: bash
        run: |
          cd /workspace/SPT/Build/server/project
          BUILD_TYPE="${{ needs.prepare.outputs.build_type }}"
          echo "Running build for $BUILD_TYPE on Linux ARM64"
          npm run build:$BUILD_TYPE -- --arch=arm64 --platform=linux
          printf "\nBuilt for Linux ARM64!\n\n"

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-artifact-linux-arm64
          path: /workspace/SPT/Build/server/project/build/
          retention-days: 1
          if-no-files-found: error

  build-docker-image:
    needs: [prepare, build-server]
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: your-dockerhub-username
      DOCKERHUB_REPOSITORY: spt-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPOSITORY }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.prepare.outputs.target_tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.prepare.outputs.target_tag }}
            type=raw,value=latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: /workspace/SPT/Build/server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/arm64
          labels: |
            org.opencontainers.image.source=https://github.com/sp-tarkov/server
            org.opencontainers.image.revision=${{ needs.build-server.outputs.server_commit }}
